(write (equal 3 (abs -3)))
(terpri)
(write (equal (+ 1 2) 3))
(terpri)
(write (equal (* 4 7) 21))
(terpri)
(write (equal (* 2 3) (+ 7 2)))
(terpri)
(write (equal (- 7 3) (* 3 2)))
(terpri)
(write (equal (abs (- 2 4)) 3))
(terpri)
