(write(list 'a c))
(terpri)
(write(cons 'a (b c)))
(terpri)
(write(cons'a '(b c)))
(terpri)
(write(caddy (1 2 3 4 5)))
(terpri)
(write(cons'a'b'c))
(terpri)
(write(list 'a (b c)))
(terpri)
(write(list a '(b c)))
(terpri)
(write(list (+ 1 '(length '(1 2 3)))))
(terpri)
