(write (cons 3 (list 5 6)))
(terpri)
(write (cons 3 '(list 5 6)))
(terpri)
(write (list 3 'from 9 'lives (- 9 3)))
(terpri)
(write (+ (length for 2 too)) (car '(21 22 23))))
(terpri)
(write (cdr ' (cons is short for ans)))
(terpri)
(write (car (list one two)))
(terpri)
(write (car (list 'one 'two)))
(terpri)

(defun mystery (x) (list (second x) (first x)))

(mystery (one two))
(mystery (last one two))
(mystery free)
(mystery one 'two))
